### ISSUE TITLE
Sagemaker dependencies

### ISSUE THREAD

**Issue by jarrettj** [aws-deepracer-community/deepracer-core#36]
Hi,

Good day.

Could you add to the Sagemaker section?:
```
pip install urllib3==1.24.3
pip install PyYAML==3.13
pip install ipython
```
From https://medium.com/@jonathantse/train-deepracer-model-locally-with-gpu-support-29cce0bdb0f9. 

Keep up the good work!

**Comment by crr0004** [comment]
I know ipython used to be used because of a couple lines in the python launch file, however it's been removed. Are you able to launch it without ipython?

I'll double check the other two as they should come in through other dependencies. They used to be there but threw errors because of other dependencies requiring different versions

**Comment by jarrettj** [comment]
What I did was go through your steps line by line on a fresh Ubuntu 18 install. And try and run sagemaker. Might be environment specific to Ubuntu? I’m not too clued up on python and pip. But for sure I had to install those to get it to run.


________________________________

**Comment by crr0004** [comment]
I have updated sagemaker python sdk setup.py file for the dependencies. The errors won't actually do any harm. Just some conflicting version constraints.
