### ISSUE TITLE
Robomaker Container Size Gets Large

### ISSUE THREAD

**Issue by dafrost22** [aws-deepracer-community/deepracer-core#41]
After running the training for extended periods of time, the robomaker container grows in size very quickly. After 8 hours it has increased 60GB. It could be easy to run out of space on smaller drives at this rate. Is there any way to optimize this?

**Comment by crr0004** [comment]
This is because it is storing all the checkpoints in the image. You can mount the volume that is storing the checkpoints with something like `-v $(readlink -f ../robo/checkpoint):/root/.ros/` as you're launching the robomaker container. At least then you can delete the checkpoints while it is still running.
